version: '3.9'

services:

    database:
        image: postgres
        container_name: database_loshermanos_dashboard
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        volumes:
            - pgdata:/data/postgres

    database_test:
            image: postgres
            container_name: loshermanos_test
            restart: always
            ports:
                - 5433:5432
            environment:
                POSTGRES_USER: ${DATABASE_USER}
                POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
                POSTGRES_DB: ${DATABASE_NAME}
            volumes:
                - pgdata:/data/postgres

    app:
        build: .
        container_name: loshermanos_dashboard
        command: sh -c "npx prisma migrate dev && npm prisma migrate"
        restart: always
        ports:
            - 5000:5000
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database

volumes:
    pgdata:
        driver: local